name: 11-1 Reuseable workflow call

on:
  push:
    paths:
      - "backend/**"

jobs:
  conditional-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Build backend Image
        uses: ctgrobin/gh-tutorial/.github/workflows/11-reusable-workflow.yml@main