
# Settings -> Secrets and Variables -> Actions -> Repository secrets ->New Repository Secret
name: Secret And variable

on:
  workflow_dispatch:

jobs:
  secret-and-variable-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Secret
        run: echo "Docker Login-- ${{secrets.DOC_USERNAME}}"

      # - name: Run Python Script
      #   run: python script.py